version: '3.4'

# launch mysql database for testing
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      # values should match the .test.env
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'secret'
